# Generated by Django 5.2.7 on 2025-10-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
